using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace StoreOperations.RMSEntities.Items
{
	public class Item
	{
		//Check out NHibernate and see if it makes this any easier
		private string _BinLocation;
		private decimal _BuydownPrice;
		private double _BuydownQuantity;
		private int _CommissionMode;
		private decimal _CommissionAmount;
		private decimal _CommissionMaximum;
		private Single _CommissionPercentProfit;
		private Single _CommissionPercentSale;
		private string _Description;
		private bool _FoodStampable;
		private int _HQID;
		private bool _ItemNotDiscountable;
		private DateTime? _LastReceived;
		private DateTime _LastUpdated;
		private string _Notes;
		private double _QuantityCommitted;
		private int _SerialNumberCount;
		private double _TareWeightPercent;
		private int _ID;
		private string _ItemLookupCode;
		private int _DepartmentID;
		private int _CategoryID;
		private int _MessageID;
		private decimal _Price;
		private decimal _PriceA;
		private decimal _PriceB;
		private decimal _PriceC;
		private decimal _SalePrice;
		private DateTime? _SaleStartDate;
		private DateTime? _SaleEndDate;
		private int _QuantityDiscountID;
		private int _TaxID;
		private short _ItemType;
		private decimal _Cost;
		private double _Quantity;
		private double _ReorderPoint;
		private double _RestockLevel;
		private double _TareWeight;
		private int _SupplierID;
		private int _TagAlongItem;
		private double _TagAlongQuantity;
		private int _ParentItem;
		private double _ParentQuantity;
		private short _BarcodeFormat;
		private decimal _PriceLowerBound;
		private decimal _PriceUpperBound;
		private string _PictureName;
		private DateTime? _LastSold;
		private string _ExtendedDescription;
		private string _SubDescription1;
		private string _SubDescription2;
		private string _SubDescription3;
		private string _UnitOfMeasure;
		private int _SubCategoryID;
		private bool _QuantityEntryNotAllowed;
		private bool _PriceMustBeEntered;
		private string _BlockSalesReason;
		private DateTime? _BlockSalesAfterDate;
		private double _Weight;
		private bool _Taxable;
		private byte[] _DBTimeStamp;
		private DateTime? _BlockSalesBeforeDate;
		private decimal _LastCost;
		private decimal _ReplacementCost;
		private bool _WebItem;
		private int _BlockSalesType;
		private int _BlockSalesScheduleID;
		private int _SaleType;
		private int _SaleScheduleID;
		private bool _Consignment;
		private bool _Inactive;
		private DateTime? _LastCounted;
		private bool _DoNotOrder;
		private decimal _MSRP;
		private DateTime _DateCreated;
		private string _Content;
		private string _UsuallyShip;
		private string _NumberFormat;
		private bool? _ItemCannotBeRet;
		private bool? _ItemCannotBeSold;
		private bool? _IsAutogenerated;
		private bool _IsGlobalvoucher;
		private bool? _DeleteZeroBalanceEntry;
		private int _TenderID;

		public string BinLocation
		{
			get { return _BinLocation; }
			set { _BinLocation = value; }
		}

		public decimal BuydownPrice
		{
			get { return _BuydownPrice; }
			set { _BuydownPrice = value; }
		}

		public double BuydownQuantity
		{
			get { return _BuydownQuantity; }
			set { _BuydownQuantity = value; }
		}

		public int CommissionMode
		{
			get { return _CommissionMode; }
			set { _CommissionMode = value; }
		}

		public decimal CommissionAmount
		{
			get { return _CommissionAmount; }
			set { _CommissionAmount = value; }
		}

		public decimal CommissionMaximum
		{
			get { return _CommissionMaximum; }
			set { _CommissionMaximum = value; }
		}

		public Single CommissionPercentProfit
		{
			get { return _CommissionPercentProfit; }
			set { _CommissionPercentProfit = value; }
		}

		public Single CommissionPercentSale
		{
			get { return _CommissionPercentSale; }
			set { _CommissionPercentSale = value; }
		}

		public string Description
		{
			get { return _Description; }
			set { _Description = value; }
		}

		public bool FoodStampable
		{
			get { return _FoodStampable; }
			set { _FoodStampable = value; }
		}

		public int HQID
		{
			get { return _HQID; }
			set { _HQID = value; }
		}

		public bool ItemNotDiscountable
		{
			get { return _ItemNotDiscountable; }
			set { _ItemNotDiscountable = value; }
		}

		public DateTime? LastReceived
		{
			get { return _LastReceived; }
			set { _LastReceived = value; }
		}

		public DateTime LastUpdated
		{
			get { return _LastUpdated; }
			set { _LastUpdated = value; }
		}

		public string Notes
		{
			get { return _Notes; }
			set { _Notes = value; }
		}

		public double QuantityCommitted
		{
			get { return _QuantityCommitted; }
			set { _QuantityCommitted = value; }
		}

		public int SerialNumberCount
		{
			get { return _SerialNumberCount; }
			set { _SerialNumberCount = value; }
		}

		public double TareWeightPercent
		{
			get { return _TareWeightPercent; }
			set { _TareWeightPercent = value; }
		}

		public int ID
		{
			get { return _ID; }
			set { _ID = value; }
		}

		public string ItemLookupCode
		{
			get { return _ItemLookupCode; }
			set { _ItemLookupCode = value; }
		}

		public int DepartmentID
		{
			get { return _DepartmentID; }
			set { _DepartmentID = value; }
		}

		public int CategoryID
		{
			get { return _CategoryID; }
			set { _CategoryID = value; }
		}

		public int MessageID
		{
			get { return _MessageID; }
			set { _MessageID = value; }
		}

		public decimal Price
		{
			get { return _Price; }
			set { _Price = value; }
		}

		public decimal PriceA
		{
			get { return _PriceA; }
			set { _PriceA = value; }
		}

		public decimal PriceB
		{
			get { return _PriceB; }
			set { _PriceB = value; }
		}

		public decimal PriceC
		{
			get { return _PriceC; }
			set { _PriceC = value; }
		}

		public decimal SalePrice
		{
			get { return _SalePrice; }
			set { _SalePrice = value; }
		}

		public DateTime? SaleStartDate
		{
			get { return _SaleStartDate; }
			set { _SaleStartDate = value; }
		}

		public DateTime? SaleEndDate
		{
			get { return _SaleEndDate; }
			set { _SaleEndDate = value; }
		}

		public int QuantityDiscountID
		{
			get { return _QuantityDiscountID; }
			set { _QuantityDiscountID = value; }
		}

		public int TaxID
		{
			get { return _TaxID; }
			set { _TaxID = value; }
		}

		public short ItemType
		{
			get { return _ItemType; }
			set { _ItemType = value; }
		}

		public decimal Cost
		{
			get { return _Cost; }
			set { _Cost = value; }
		}

		public double Quantity
		{
			get { return _Quantity; }
			set { _Quantity = value; }
		}

		public double ReorderPoint
		{
			get { return _ReorderPoint; }
			set { _ReorderPoint = value; }
		}

		public double RestockLevel
		{
			get { return _RestockLevel; }
			set { _RestockLevel = value; }
		}

		public double TareWeight
		{
			get { return _TareWeight; }
			set { _TareWeight = value; }
		}

		public int SupplierID
		{
			get { return _SupplierID; }
			set { _SupplierID = value; }
		}

		public int TagAlongItem
		{
			get { return _TagAlongItem; }
			set { _TagAlongItem = value; }
		}

		public double TagAlongQuantity
		{
			get { return _TagAlongQuantity; }
			set { _TagAlongQuantity = value; }
		}

		public int ParentItem
		{
			get { return _ParentItem; }
			set { _ParentItem = value; }
		}

		public double ParentQuantity
		{
			get { return _ParentQuantity; }
			set { _ParentQuantity = value; }
		}

		public short BarcodeFormat
		{
			get { return _BarcodeFormat; }
			set { _BarcodeFormat = value; }
		}

		public decimal PriceLowerBound
		{
			get { return _PriceLowerBound; }
			set { _PriceLowerBound = value; }
		}

		public decimal PriceUpperBound
		{
			get { return _PriceUpperBound; }
			set { _PriceUpperBound = value; }
		}

		public string PictureName
		{
			get { return _PictureName; }
			set { _PictureName = value; }
		}

		public DateTime? LastSold
		{
			get { return _LastSold; }
			set { _LastSold = value; }
		}

		public string ExtendedDescription
		{
			get { return _ExtendedDescription; }
			set { _ExtendedDescription = value; }
		}

		public string SubDescription1
		{
			get { return _SubDescription1; }
			set { _SubDescription1 = value; }
		}

		public string SubDescription2
		{
			get { return _SubDescription2; }
			set { _SubDescription2 = value; }
		}

		public string SubDescription3
		{
			get { return _SubDescription3; }
			set { _SubDescription3 = value; }
		}

		public string UnitOfMeasure
		{
			get { return _UnitOfMeasure; }
			set { _UnitOfMeasure = value; }
		}

		public int SubCategoryID
		{
			get { return _SubCategoryID; }
			set { _SubCategoryID = value; }
		}

		public bool QuantityEntryNotAllowed
		{
			get { return _QuantityEntryNotAllowed; }
			set { _QuantityEntryNotAllowed = value; }
		}

		public bool PriceMustBeEntered
		{
			get { return _PriceMustBeEntered; }
			set { _PriceMustBeEntered = value; }
		}

		public string BlockSalesReason
		{
			get { return _BlockSalesReason; }
			set { _BlockSalesReason = value; }
		}

		public DateTime? BlockSalesAfterDate
		{
			get { return _BlockSalesAfterDate; }
			set { _BlockSalesAfterDate = value; }
		}

			public double Weight
		{
			get { return _Weight; }
			set { _Weight = value; }
		}

		public bool Taxable
		{
			get { return _Taxable; }
			set { _Taxable = value; }
		}

		public byte[] DBTimeStamp
		{
			get { return _DBTimeStamp; }
			set { _DBTimeStamp = value; }
		}

		public DateTime? BlockSalesBeforeDate
		{
			get { return _BlockSalesBeforeDate; }
			set { _BlockSalesBeforeDate = value; }
		}

		public decimal LastCost
		{
			get { return _LastCost; }
			set { _LastCost = value; }
		}

		public decimal ReplacementCost
		{
			get { return _ReplacementCost; }
			set { _ReplacementCost = value; }
		}

		public bool WebItem
		{
			get { return _WebItem; }
			set { _WebItem = value; }
		}

		public int BlockSalesType
		{
			get { return _BlockSalesType; }
			set { _BlockSalesType = value; }
		}

		public int BlockSalesScheduleID
		{
			get { return _BlockSalesScheduleID; }
			set { _BlockSalesScheduleID = value; }
		}

		public int SaleType
		{
			get { return _SaleType; }
			set { _SaleType = value; }
		}

		public int SaleScheduleID
		{
			get { return _SaleScheduleID; }
			set { _SaleScheduleID = value; }
		}

		public bool Consignment
		{
			get { return _Consignment; }
			set { _Consignment = value; }
		}

		public bool Inactive
		{
			get { return _Inactive; }
			set { _Inactive = value; }
		}

		public DateTime? LastCounted
		{
			get { return _LastCounted; }
			set { _LastCounted = value; }
		}

		public bool DoNotOrder
		{
			get { return _DoNotOrder; }
			set { _DoNotOrder = value; }
		}

		public decimal MSRP
		{
			get { return _MSRP; }
			set { _MSRP = value; }
		}

		public DateTime DateCreated
		{
			get { return _DateCreated; }
			set { _DateCreated = value; }
		}

		public string Content
		{
			get { return _Content; }
			set { _Content = value; }
		}

		public string UsuallyShip
		{
			get { return _UsuallyShip; }
			set { _UsuallyShip = value; }
		}

		public string NumberFormat
		{
			get { return _NumberFormat; }
			set { _NumberFormat = value; }
		}

		public bool? ItemCannotBeRet
		{
			get { return _ItemCannotBeRet; }
			set { _ItemCannotBeRet = value; }
		}

		public bool? ItemCannotBeSold
		{
			get { return _ItemCannotBeSold; }
			set { _ItemCannotBeSold = value; }
		}

		public bool? IsAutogenerated
		{
			get { return _IsAutogenerated; }
			set { _IsAutogenerated = value; }
		}

		public bool IsGlobalvoucher
		{
			get { return _IsGlobalvoucher; }
			set { _IsGlobalvoucher = value; }
		}

		public bool? DeleteZeroBalanceEntry
		{
			get { return _DeleteZeroBalanceEntry; }
			set { _DeleteZeroBalanceEntry = value; }
		}

		public int TenderID
		{
			get { return _TenderID; }
			set { _TenderID = value; }
		}

	}
}
